arr = [1,2,3];
arr.push(4);
console.log(arr, arr.length);
arr.splice(2,0,5,7);
console.log(arr, arr.length);
arr = arr.concat(12,23);
console.log(arr, arr.length);
arr.shift();
arr.pop();
console.log(arr, arr.length);
arr.splice(2,2);
console.log(arr, arr.length);
delete arr[2];
console.log(arr, arr.length);
let f = arr.find(e => e === 5);
console.log(f);
console.log(arr.indexOf(5));
console.log(arr.sort());
console.log(arr.reverse());